# Generated by Django 5.2.10 on 2026-02-26 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useractivity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['user', 'post'], name='useractivit_user_id_5a626b_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'created_at'], name='useractivit_post_id_fceafc_idx'),
        ),
    ]
