# Generated by Django 5.2.10 on 2026-02-09 06:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('direct', 'Direct Message'), ('group', 'Group Chat'), ('match', 'Match Conversation'), ('support', 'Support Chat')], db_index=True, default='direct', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_photo', models.ImageField(blank=True, null=True, upload_to='group_photos/%Y/%m/')),
                ('is_private', models.BooleanField(default=True)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.JSONField(default=dict)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_chats', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(db_index=True, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_chats', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='chat.chatconversation')),
            ],
        ),
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_members', models.IntegerField(default=50)),
                ('join_by_invite', models.BooleanField(default=True)),
                ('allow_media', models.BooleanField(default=True)),
                ('allow_forwarding', models.BooleanField(default=True)),
                ('theme_color', models.CharField(default='#0084FF', max_length=7)),
                ('custom_emoji', models.JSONField(blank=True, default=list)),
                ('banned_users', models.ManyToManyField(blank=True, related_name='banned_from_groups', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_group', to='chat.chatconversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('moderators', models.ManyToManyField(blank=True, related_name='moderated_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Group',
                'verbose_name_plural': 'Chat Groups',
            },
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_message', models.BooleanField(default=True)),
                ('notify_message_sound', models.BooleanField(default=True)),
                ('notify_message_preview', models.BooleanField(default=True)),
                ('notify_group_mentions', models.BooleanField(default=True)),
                ('show_last_seen', models.BooleanField(default=True)),
                ('show_online_status', models.BooleanField(default=True)),
                ('show_read_receipts', models.BooleanField(default=True)),
                ('allow_screenshots', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='light', max_length=20)),
                ('font_size', models.IntegerField(default=16)),
                ('enter_to_send', models.BooleanField(default=True)),
                ('auto_download_media', models.BooleanField(default=False)),
                ('media_download_size_limit', models.IntegerField(default=10485760)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('blocked_users', models.ManyToManyField(blank=True, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('location', 'Location'), ('contact', 'Contact'), ('system', 'System Message')], db_index=True, default='text', max_length=10)),
                ('content', models.TextField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to='chat_media/%Y/%m/')),
                ('media_thumbnail', models.ImageField(blank=True, null=True, upload_to='chat_thumbnails/')),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('reactions', models.JSONField(default=dict)),
                ('is_deleted_for_everyone', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatconversation')),
                ('deleted_for', models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL)),
                ('original_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='chat.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Message Statuses',
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['updated_at'], name='chat_chatco_updated_de31b0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['conversation_type', 'is_active'], name='chat_chatco_convers_9737ae_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['created_at'], name='chat_chatco_created_31a4ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatarchive',
            unique_together={('user', 'conversation')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__b02346_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read', 'created_at'], name='chat_messag_is_read_e16b95_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'created_at'], name='chat_messag_message_bcd8ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagestatus',
            unique_together={('message', 'user')},
        ),
    ]
