# Generated by Django 5.2.10 on 2026-02-09 06:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('signup', 'User Signup'), ('login', 'User Login'), ('logout', 'User Logout'), ('profile_view', 'Profile View'), ('profile_update', 'Profile Updated'), ('profile_approved', 'Profile Approved'), ('profile_unapproved', 'Profile Unapproved'), ('like_sent', 'Like Sent'), ('like_received', 'Like Received'), ('match', 'New Match'), ('message_sent', 'Message Sent'), ('friend_request', 'Friend Request'), ('friend_added', 'Friend Added'), ('password_change', 'Password Changed'), ('email_change', 'Email Changed'), ('account_delete', 'Account Deleted'), ('preferences_saved', 'Preferences Saved'), ('landing_page_submit', 'Landing Page Submitted')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('additional_info', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_activities_targeting', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type', 'created_at'], name='accounts_ac_user_id_da84e6_idx'), models.Index(fields=['activity_type', 'created_at'], name='accounts_ac_activit_0b5ba0_idx'), models.Index(fields=['created_at'], name='accounts_ac_created_936747_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Verification',
                'verbose_name_plural': 'Email Verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_verified', 'created_at'], name='accounts_em_is_veri_e3e6ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='LandingPageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('preferences', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('converted_to_user', models.BooleanField(db_index=True, default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Landing Page Submission',
                'verbose_name_plural': 'Landing Page Submissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['converted_to_user', 'created_at'], name='accounts_la_convert_ec4fd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Token',
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_pa_user_id_8cd138_idx'), models.Index(fields=['used', 'created_at'], name='accounts_pa_used_57f948_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], db_index=True, max_length=1)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y/%m/')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('sect', models.CharField(blank=True, help_text='Religious or philosophical sect', max_length=100)),
                ('education', models.CharField(blank=True, choices=[('HS', 'High School'), ('AD', 'Associate Degree'), ('BD', "Bachelor's Degree"), ('MD', "Master's Degree"), ('PHD', 'Doctorate'), ('OT', 'Other')], max_length=10)),
                ('practice_level', models.CharField(blank=True, choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced'), ('E', 'Expert')], max_length=1)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(db_index=True, default=True)),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('completed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_profile_update', models.DateTimeField(blank=True, null=True)),
                ('show_age', models.BooleanField(default=True)),
                ('show_location', models.BooleanField(default=True)),
                ('show_sect', models.BooleanField(default=True)),
                ('show_education', models.BooleanField(default=True)),
                ('show_practice_level', models.BooleanField(default=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('landing_page', 'Landing Page'), ('direct_signup', 'Direct Signup')], default='landing_page', max_length=50)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_visible', 'approved', 'completed'], name='accounts_us_is_visi_2e11e3_idx'), models.Index(fields=['gender', 'age'], name='accounts_us_gender_9d15f9_idx'), models.Index(fields=['city', 'country'], name='accounts_us_city_9a6f33_idx'), models.Index(fields=['last_active'], name='accounts_us_last_ac_e1a878_idx')],
            },
        ),
    ]
