# Generated by Django 5.2.10 on 2026-02-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sect',
            field=models.CharField(blank=True, choices=[('sunni_barelvi', 'Sunni / Barelvi'), ('deobandi', 'Deobandi'), ('ehl_e_hadith', 'Ehl-e-Hadith / Wahabi'), ('shia', 'Shia'), ('other', 'Other')], help_text='Islamic sect', max_length=50),
        ),
    ]
