# Generated by Django 5.2.10 on 2026-02-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_sect'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
