# Generated by Django 5.2.10 on 2026-02-09 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('strangers', 'Strangers'), ('pending_sender', 'Pending (Sender)'), ('pending_receiver', 'Pending (Receiver)'), ('friends', 'Friends'), ('rejected_by_b', 'Rejected by B'), ('rejected_by_a', 'Rejected by A'), ('blocked_by_a', 'Blocked by A'), ('blocked_by_b', 'Blocked by B'), ('unfriended_by_a', 'Unfriended by A'), ('unfriended_by_b', 'Unfriended by B')], db_index=True, default='strangers', max_length=20)),
                ('status_before_block', models.CharField(blank=True, choices=[('strangers', 'Strangers'), ('pending_sender', 'Pending (Sender)'), ('pending_receiver', 'Pending (Receiver)'), ('friends', 'Friends'), ('rejected_by_b', 'Rejected by B'), ('rejected_by_a', 'Rejected by A'), ('blocked_by_a', 'Blocked by A'), ('blocked_by_b', 'Blocked by B'), ('unfriended_by_a', 'Unfriended by A'), ('unfriended_by_b', 'Unfriended by B')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_actions', to=settings.AUTH_USER_MODEL)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendships_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user_a', 'user_b'], name='friendship__user_a__ef4aba_idx'), models.Index(fields=['user_a', 'status'], name='friendship__user_a__21c71b_idx'), models.Index(fields=['user_b', 'status'], name='friendship__user_b__c05923_idx'), models.Index(fields=['status', 'updated_at'], name='friendship__status_c0f306_idx')],
                'unique_together': {('user_a', 'user_b')},
            },
        ),
        migrations.CreateModel(
            name='ProfileLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mutual', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_profile_likes', to=settings.AUTH_USER_MODEL)),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_profile_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['liker', 'created_at'], name='friendship__liker_i_87be56_idx'), models.Index(fields=['liked', 'created_at'], name='friendship__liked_i_f06b3d_idx'), models.Index(fields=['is_mutual'], name='friendship__is_mutu_0cb304_idx'), models.Index(fields=['created_at'], name='friendship__created_51e2cd_idx')],
                'unique_together': {('liker', 'liked')},
            },
        ),
    ]
